### ISSUE TITLE
Создание модели Account

### ISSUE THREAD

**Issue by yedige87** [TagleD/headhunter#2]

**Comment by yedige87** [comment]
**Для чего это нужно?**

Создание модели Account необходимо для аутентификации пользователей приложения Headhunter

**Как это сделать?**
В pycharm создаем приложение (директорию) _name_
В указанной директории создаем файл models
В файле models создаем class Account с следующими полями и соответствующими атрибутами: email, user_type, full_name, phone, avatar(необязательное поле)
Добавляем класс UserTypeChoice с полями: APPLICANT и COMPANY
Делаем миграцию в БД headhunter

**Критерии приема**
После миграции в БД появляется таблица Account

**Планируемое время работы 1 час**

**Comment by TagleD** [comment]
Выполнили за 2 часа
