### ISSUE TITLE
Создание базового шаблона и приведения текущей части проекта к нормальному виду

### ISSUE THREAD

**Issue by TagleD** [TagleD/headhunter#7]
### Для чего это нужно?
Для того, чтобы был единый стиль у всех страниц проекта и пользователь с удобством мог пользоваться функционалом сайта

### Как это сделать?

1. Подключить в settings.py статику через STATICFILES_DIRS.BASE_DIR = 'static'
2. Создать директорию в репозитории проекта с тремя директориями: img и static js
3. Добавить в директорию static файл style.css
4. Сделать базовый шаблон base.html, который будем использовать на всех страницах
5. Стилизовать страницу для регистрации пользователя и добавить кнопку "войти", если у пользователя аккаунт уже существует
6. Стилизовать страницу для аутентификации пользователя и добавить кнопку "зарегистрироваться", если у пользователя аккаунта еще нет
7.  В регистрации с помощью js менять label поля name:
    -Если ChoiceFiled на соискателе, то label 'Имя пользователя'
    -Если ChoiceFiled на работодателе, то label 'Имя компании'

Критерии приема
Созданы директории со статистическими файлами
Сделан базовый шаблон
Стилизована страница регистрации
Стилизована страница аутентификации
В регистрации в зависимости от выбора user_type выводится нужный label

### Планируемое время - 4ч.

**Comment by yedige87** [comment]
Потратили 5ч.
